kind: Service
apiVersion: v1
metadata:
  name: "monolith"
spec:
  selector:
    app: "monolith"
    secure: "enabled"
  ports:
    - name: https
      protocol: "TCP"
      port: 443
      targetPort: 443
  type: ClusterIP